In [18]:
import numpy as np

arr = np.array([[1, 0, 3], [0, 5, 0]])
indices = np.where((arr) > 0)
print(indices)
# 输出：(array([0, 0, 1]), array([0, 2, 1]))

(array([0, 0, 1]), array([0, 2, 1]))


In [11]:
arr-1

array([[ 0, -1,  2],
       [-1,  4, -1]])

In [17]:
import torch

tensor = torch.tensor([[1, 0, 3], [0, 5, 0]])
indices = torch.where(tensor>0)
print(indices)
# 输出：
# tensor([[0, 0],
#         [0, 2],
#         [1, 1]])

(tensor([0, 0, 1]), tensor([0, 2, 1]))


In [10]:
tensor-1

tensor([[ 0, -1,  2],
        [-1,  4, -1]])